services:
  - type: web
    name: yango-api
    env: node
    rootDir: backend
    buildCommand: yarn install --production=false && yarn build && ./node_modules/.bin/prisma generate
    startCommand: yarn start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
